import { WorkCategory } from "../models/category.model";
import { Work } from "../models/work.model";

export const WORKS: { [key in WorkCategory]: Work[] } = {
  COMMUNICATION: [
    {
      id: 1,
      teamName: null,
      designer: [{ nameKo: "박승주", studentId: 21700271 }],
      title: "하마hamma",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 2,
      teamName: null,
      designer: [{ nameKo: "안희재", studentId: 21700427 }],
      title: "To:Gather",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 3,
      teamName: null,
      designer: [{ nameKo: "박승주", studentId: 21800297 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 4,
      teamName: null,
      designer: [{ nameKo: "박창조", studentId: 21800323 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 5,
      teamName: null,
      designer: [{ nameKo: "송민준", studentId: 21800393 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 6,
      teamName: null,
      designer: [{ nameKo: "이하준", studentId: 21800595 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 7,
      teamName: null,
      designer: [{ nameKo: "최가흔", studentId: 21800722 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 8,
      teamName: null,
      designer: [{ nameKo: "강수빈", studentId: 21900006 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 9,
      teamName: null,
      designer: [{ nameKo: "고수영", studentId: 21900025 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 10,
      teamName: null,
      designer: [{ nameKo: "김가현", studentId: 21900061 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 11,
      teamName: null,
      designer: [{ nameKo: "김경진", studentId: 21900067 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 12,
      teamName: null,
      designer: [{ nameKo: "김나경", studentId: 21900074 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 13,
      teamName: null,
      designer: [{ nameKo: "김성순", studentId: 21900114 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 14,
      teamName: null,
      designer: [{ nameKo: "박은실", studentId: 21900299 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 15,
      teamName: null,
      designer: [{ nameKo: "서유나", studentId: 21900365 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 16,
      teamName: null,
      designer: [{ nameKo: "안다진", studentId: 21900417 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 17,
      teamName: null,
      designer: [{ nameKo: "이동연", studentId: 21900494 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 18,
      teamName: null,
      designer: [{ nameKo: "이지향", studentId: 21900569 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 19,
      teamName: null,
      designer: [{ nameKo: "이현화", studentId: 21900598 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 20,
      teamName: null,
      designer: [{ nameKo: "정해인", studentId: 21900653 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 21,
      teamName: null,
      designer: [{ nameKo: "조은비", studentId: 21900709 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 22,
      teamName: null,
      designer: [{ nameKo: "강지은", studentId: 21901003 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 23,
      teamName: null,
      designer: [{ nameKo: "김수아", studentId: 22000110 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 24,
      teamName: null,
      designer: [{ nameKo: "김은빈", studentId: 22000160 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 25,
      teamName: null,
      designer: [{ nameKo: "노유원", studentId: 22000227 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 26,
      teamName: null,
      designer: [{ nameKo: "박보민", studentId: 22000260 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 27,
      teamName: null,
      designer: [{ nameKo: "서하령", studentId: 22000353 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 28,
      teamName: null,
      designer: [{ nameKo: "안가현", studentId: 22000399 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 29,
      teamName: null,
      designer: [{ nameKo: "유주희", studentId: 22000465 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 30,
      teamName: null,
      designer: [{ nameKo: "이주아", studentId: 22000565 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 31,
      teamName: null,
      designer: [{ nameKo: "이주영", studentId: 22000566 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 32,
      teamName: null,
      designer: [{ nameKo: "임예담", studentId: 22000615 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 33,
      teamName: null,
      designer: [{ nameKo: "장소윤", studentId: 22000622 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 34,
      teamName: null,
      designer: [{ nameKo: "전유은", studentId: 22000651 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 35,
      teamName: null,
      designer: [{ nameKo: "정예은", studentId: 22000681 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 36,
      teamName: null,
      designer: [{ nameKo: "정은서", studentId: 22000686 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 37,
      teamName: null,
      designer: [{ nameKo: "김현지", studentId: 22001014 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 38,
      teamName: null,
      designer: [{ nameKo: "류혜빈", studentId: 22001019 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 39,
      teamName: null,
      designer: [{ nameKo: "임다솔", studentId: 22001057 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 40,
      teamName: null,
      designer: [{ nameKo: "장희진", studentId: 22001058 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 41,
      teamName: null,
      designer: [{ nameKo: "최예영", studentId: 22001069 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 42,
      teamName: null,
      designer: [{ nameKo: "정희주", studentId: 22100696 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
  ],
  SERVICE: [
    {
      id: 1,
      teamName: "4패트",
      designer: [
        { nameKo: "김수아", studentId: 22000110 },
        { nameKo: "김은빈", studentId: 22000160 },
        { nameKo: "박보민", studentId: 22000260 },
        { nameKo: "이주영", studentId: 22000566 },
      ],
      title: "예시 타이틀1",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 2,
      teamName: "깔쌈랄키",
      designer: [
        { nameKo: "이하준", studentId: 21800595 },
        { nameKo: "안다진", studentId: 21900417 },
        { nameKo: "이동연", studentId: 21900494 },
        { nameKo: "정희주", studentId: 22100696 },
      ],
      title: "예시 타이틀2",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 3,
      teamName: "둥둥",
      designer: [
        { nameKo: "고수영", studentId: 21900025 },
        { nameKo: "김가현", studentId: 21900061 },
        { nameKo: "김성순", studentId: 21900114 },
        { nameKo: "서하령", studentId: 22000353 },
      ],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 4,
      teamName: "디두",
      designer: [
        { nameKo: "박승주", studentId: 21800297 },
        { nameKo: "박창조", studentId: 21800323 },
        { nameKo: "정은서", studentId: 22000686 },
        { nameKo: "김현지", studentId: 22001014 },
      ],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 5,
      teamName: "삼자대면",
      designer: [
        { nameKo: "송민준", studentId: 21800393 },
        { nameKo: "노유원", studentId: 22000227 },
        { nameKo: "임다솔", studentId: 22001057 },
      ],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 6,
      teamName: "싸그리",
      designer: [
        { nameKo: "박승주", studentId: 21700271 },
        { nameKo: "정해인", studentId: 21900653 },
        { nameKo: "임예담", studentId: 22000615 },
        { nameKo: "장희진", studentId: 22001058 },
      ],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 7,
      teamName: "오브",
      designer: [
        { nameKo: "김나경", studentId: 21900074 },
        { nameKo: "이지향", studentId: 21900569 },
        { nameKo: "이주아", studentId: 22000565 },
        { nameKo: "정예은", studentId: 22000681 },
      ],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 8,
      teamName: "정준하",
      designer: [
        { nameKo: "강수빈", studentId: 21900006 },
        { nameKo: "이현화", studentId: 21900598 },
        { nameKo: "전유은", studentId: 22000651 },
        { nameKo: "류혜빈", studentId: 22001019 },
      ],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 9,
      teamName: "티거",
      designer: [
        { nameKo: "안희재", studentId: 21700427 },
        { nameKo: "유주희", studentId: 22000465 },
        { nameKo: "최예영", studentId: 22001069 },
      ],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 10,
      teamName: "하마하마",
      designer: [
        { nameKo: "서유나", studentId: 21900365 },
        { nameKo: "조은비", studentId: 21900709 },
        { nameKo: "강지은", studentId: 21901003 },
        { nameKo: "장소윤", studentId: 22000622 },
      ],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 11,
      teamName: "DMG",
      designer: [
        { nameKo: "최가흔", studentId: 21800722 },
        { nameKo: "김경진", studentId: 21900067 },
        { nameKo: "박은실", studentId: 21900299 },
        { nameKo: "안가현", studentId: 22000399 },
      ],
      title: "",
      gridImg: "",
      mainImg: "",
    },
  ],
  UXUI: [
    {
      id: 1,
      teamName: "해디크",
      designer: [
        { nameKo: "조가은", studentId: 21900692 },
        { nameKo: "권은진", studentId: 22000043 },
        { nameKo: "안혜빈", studentId: 22000405 },
        { nameKo: "유수정", studentId: 22100464 },
      ],
      title: "예시 타이틀1",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 2,
      teamName: "BO3",
      designer: [
        { nameKo: "최석현", studentId: 21700722 },
        { nameKo: "김민경", studentId: 22000070 },
        { nameKo: "허현지", studentId: 22000798 },
        { nameKo: "이하영", studentId: 22100590 },
      ],
      title: "예시 타이틀2",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 3,
      teamName: "LUX",
      designer: [
        { nameKo: "강산길", studentId: 21700003 },
        { nameKo: "김민영", studentId: 21900098 },
        { nameKo: "신지수", studentId: 22000392 },
        { nameKo: "임시은", studentId: 22000613 },
      ],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 4,
      teamName: "Salty",
      designer: [
        { nameKo: "한인철", studentId: 21800781 },
        { nameKo: "김유미", studentId: 21900166 },
        { nameKo: "이지원", studentId: 22000581 },
        { nameKo: "서지은", studentId: 22100369 },
        { nameKo: "이석영", studentId: 22435003 },
      ],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 5,
      teamName: "Vivaz",
      designer: [
        { nameKo: "한상윤", studentId: 21800775 },
        { nameKo: "박예봄", studentId: 21801030 },
        { nameKo: "신수민", studentId: 21900396 },
        { nameKo: "조은비", studentId: 22000723 },
      ],
      title: "",
      gridImg: "",
      mainImg: "",
    },
  ],
  PRODUCT: [
    {
      id: 1,
      teamName: null,
      designer: [{ nameKo: "박범서", studentId: 21600252 }],
      title: "예시 타이틀1",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 2,
      teamName: null,
      designer: [{ nameKo: "이승현", studentId: 21701033 }],
      title: "예시 타이틀2",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 3,
      teamName: null,
      designer: [{ nameKo: "김형진", studentId: 21800204 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 4,
      teamName: null,
      designer: [{ nameKo: "이신원", studentId: 21801053 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 5,
      teamName: null,
      designer: [{ nameKo: "김민기", studentId: 21900093 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
    {
      id: 6,
      teamName: null,
      designer: [{ nameKo: "박민석", studentId: 21900267 }],
      title: "",
      gridImg: "",
      mainImg: "",
    },
  ],
};
